# 1. Usamos una imagen base de Node.js
FROM node:18-alpine

# 2. Configuramos el directorio de trabajo
WORKDIR /app

# 3. Copiamos los archivos necesarios
COPY package*.json ./

# 4. Instalamos dependencias
RUN npm install

# 5. Copiamos el resto de los archivos
COPY . .


# 7. Exponemos el puerto 3000
EXPOSE 3000

# 8. Comando para iniciar el servidor
#CMD ["npm", "run", "dev"] # Cambiaremos a "start" en producción

CMD npm run dev



