version: '3.9'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: bopaa
    depends_on:
      - mysql

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bopaa
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




#docker compose build --no-cache