# 1. Usamos una imagen base de Node.js
FROM node:18-alpine

# 2. Configuramos el directorio de trabajo dentro del contenedor
WORKDIR /app

# 3. Copiamos los archivos del proyecto
COPY package*.json ./

# 4. Instalamos las dependencias
RUN npm install

# 5. Copiamos el resto de los archivos del proyecto
COPY . .

# 6. Exponemos el puerto 8080
EXPOSE 8080

# 7. Comando para iniciar el servidor en desarrollo
CMD ["npm", "run", "start:dev"]





